 	ORG 0000H
	MOV SP,#50H
	MOV R4,#00H		; ROMOVE ANY GARBAGE VALUE FROM R4 TO PREVENT EXTRA DELAYS IN DELAY ROUTUNE


	; ----READY DISPLAY---

	LCALL DELAY1
	MOV A, #38H	; INTI...LCD 2 LINE 5 *7 MATRIX
	LCALL WRTCMD
	MOV A, #0EH	; LCD ON AND CURSOR ON
	LCALL WRTCMD
	MOV A, #01H ; CLEAR LCD
	LCALL WRTCMD

	; ---- DISPLAYING MSG -----
	LCALL DELAY1  
	MOV DPTR,#WLCMMSG
	LCALL DISP_MSG
	LCALL DELAY			; DELAY BETWEEN TWO MSGS
	MOV DPTR,#FNLMSG
	LCALL DISP_MSG
	LCALL DELAY
	MOV DPTR,#SLTSINE
	LCALL DISP_MSG
	LCALL DELAY
	MOV DPTR,#WV_TYPE
	LCALL DISP_MSG
	MOV A,#80H		; MOVING CURSOR TO FIRST POSITION
	LCALL WRTCMD

	;------keyboard functions--------

	LCALL KEYBOARD


	SJMP $



;;-------------ALL CALLS ------------------------;;

WLCMMSG:DB "WELCOME TO MSU BARODA!"
FNLMSG:DB "FINAL YEAR PROJECT!"
SLTSINE:DB "SELECT WAVEFORM YOU WANT TO SEE!"
WV_TYPE:DB "1  SINE WAVE    2  3RD HARMONIC!"

	;-------KEYBOARD INTERFACING-----

KEYBOARD:MOV P2,#0F0H		; MAKING AS READING PORT
WAIT:LCALL KEYSDOWN			; CHECK IF NO KEY IS PRESSED OR NOT
	JZ WAIT
	LCALL CONVERT			;CHECK FOR SINGLE KEY IS PRESSED OR NOT
	JNB VALIDKEY,WAIT
	MOV NEWKEY,A			; --??? DECLARING OF NEWKEY && VALIDKEY REMAINING.
	LCALL 					; --??? DELAY FOR KEYBOARD NOISE IS REMAINIG
	LCALL KEYSDOWN
	JZ WAIT
	LCALL CONVERT
	JNB VALIDKEY,WAIT
	CJNE NEWKEY,A,WAIT
	RET

CONVERT:CLR VALIDKEY
	CLR A
	MOV A,P2
	ORL A, #0FH
	CJNE A,#01111111B,CH1
	SJMP FOUND
CH1:CJNE A, #10111111B,CH2
	SJMP FOUND
CH2:CJNE A, #11011111B,CH3
	SJMP FOUND
CH3:CJNE A, #11101111B,CH4
FOUND:SETB VALIDKEY
CH4:RET

KEYSDOWN:MOV A,P2	; LAST 4 PIN OF THE PORT P2 FOR UP,DOWN,OKAY,RESET
	ORL A, #0FH
	CPL A
	RET

;----delay subroutine---
DELAY:MOV R4,#3		; ADD NUMBER OF SEC 
DELAY1:MOV R5,#10	; FROM HERE ---1 SECOND DELAY
D2:	MOV R6,#200
D1:	MOV R7,#250
HERE:DJNZ R7,HERE
	DJNZ R6,D1
	DJNZ R5,D2
	DJNZ R4,DELAY1
	RET

;-----display 16 character in LCD---

DISP_MSG:MOV A,#01H		; CLEAR LCD BEFORE DISPLAYING OTHER MSG
	LCALL WRTCMD
	MOV A,#80H	; FORCE CURSOR POSITION TO FIRST
	LCALL WRTCMD
	MOV B,#16	; FOR 16 CHARACTER  IN THE MSG BODY
L1:	CLR A
	MOVC A, @A+ DPTR
	CJNE A,#21H,CON1	;COMPARING '!' WITH ASCII 21H SO THAT END OF MSG AND EXIT LOOP
	SJMP RETURN
CON1:LCALL WRT_DATA
	INC DPTR
	DJNZ B,L1	; WHEN IT EXIT 1ST LINE WILL DISPLAY 16 CHARACTER
	MOV A,#0C0H	; SENDING CURSOR TO 2ND ROW FIRST POSTION
	LCALL WRTCMD
	MOV B,#16
L2: CLR A
	MOVC A,@A+DPTR
	CJNE A,#21H,CON2	;COMPARING '!' WITH ASCII 21h
	SJMP RETURN
CON2:LCALL WRT_DATA
	INC DPTR
	DJNZ B,L2
RETURN:RET

;------command and write subroutine for LCD---

WRTCMD:LCALL ISREADY	
	MOV P1,A
	CLR P2.0	; RS = 0 FOR COMMAND
	CLR P2.1	; R/W = 0 FOR WRITTING 
	SETB P2.2	; ENABLE SIGNAL
	CLR P2.2
	RET

WRT_DATA:LCALL ISREADY
	MOV P1,A
	SETB P1.0	; RS = 1 FOR DATA
	CLR P2.1	; R/W = 0 FOR WRITTING TO DISPLAY
	SETB P2.2	;ENABLE SIGNAL
	CLR P2.2	  ,D
	RET

;-----check if D7 bit is busy or not---

ISREADY:SETB P1.7	; READING AS INPUT BIT OR PORT
	CLR P2.0	  ; RS = 0 AS COMMAND
	SETB P2.1	; R/W = 1 FOR READING COMMAND
BUSY:CLR P2.2	; ENABLE SIGNAL
	SETB P2.2
	JB P1.7,BUSY
	CLR P2.2
	RET

	END