	VALIDKEY EQU 00H
	NEWKEY EQU 00H
	UPKEY EQU 0FEH
	DOWNKEY EQU 0FDH
	OKKEY EQU 0FBH
	RSTKY EQU 0F7H
START:
	ORG 0000H
	MOV SP,#50H
	

	; ----READY DISPLAY---
	MOV R4,#01H		; ROMOVE ANY GARBAGE VALUE FROM R4 TO PREVENT EXTRA DELAYS IN DELAY ROUTUNE
	LCALL DELAY1
	MOV A, #38H	; INTI...LCD 2 LINE 5 *7 MATRIX
	LCALL WRTCMD
	MOV A, #0EH	; LCD ON AND CURSOR ON
	LCALL WRTCMD
	MOV A, #01H ; CLEAR LCD
	LCALL WRTCMD

	; ---- DISPLAYING MSG -----
	MOV R4,#01H
	LCALL DELAY1  
	MOV DPTR,#WLCMMSG
	LCALL DISP_MSG
	LCALL DELAY			; DELAY BETWEEN TWO MSGS
	MOV DPTR,#FNLMSG
	LCALL DISP_MSG
	LCALL DELAY
	MOV DPTR,#SLTSINE
	LCALL DISP_MSG
	LCALL DELAY
	MOV DPTR,#WV_TYPE
	LCALL DISP_MSG
	MOV A,#80H; MOVING CURSOR TO FIRST POSITION
	MOV R1,A	;CURSOR LOCATION IN R1
	LCALL WRTCMD

	;------keyboard functions--------

	LCALL KBD
	CJNE R1,# 80H,HARMO
	MOV DPTR,#SNWAVE
HARMO:CJNE R1,#0C0H,SRT
	MOV DPTR,#H_WAVE

	;--------selecting frequency---------
SRT:MOV A,#80H
	MOV R1,A
	LCALL WRTCMD
SRT1:LCALL KEYBOARD
	MOV A,NEWKEY
	CJNE A,#RSTKY,F1
	LJMP START
F1: CJNE A,#OKKEY,F2
	RET ;----------RETURN WIHT SOME DELAY ROUTINE-----
F2: CJNE A,#UPKEY,F3
	CJNE R1,#80H,F11
	MOV A,#0C0H
	MOV R1,A
	LCALL WRTCMD
	SJMP SRT1
F11:CJNE R1,#88H,F12
	MOV A,#80H
	MOV R1,A
	LCALL WRTCMD
	SJMP SRT1
F12:CJNE R1,#0C0H,SRT1
	MOV A,#88H
	MOV R1,A
	LCALL WRTCMD
	SJMP SRT1
F3:CJNE A,#DOWNKEY,SRT1
	CJNE R1,#80H,F21
	MOV A,#88H
	MOV R1,A
	LCALL WRTCMD
	SJMP SRT1
F21:CJNE R1,#88H,F22
	MOV A,#0C0H
	MOV R1,A
	LCALL WRTCMD
	SJMP SRT1
F22:CJNE R1,#0C0H,SRT1
	MOV A,#80H
	MOV R1,A
	LCALL WRTCMD
	SJMP SRT1

	;---------FREQ SELECTED------

	CJNE R1,#80H,S2
	MOV PC,#SNDLY
S2:CJNE R1,#88H,S1
	MOV PC,#SNDLY1
S1:CJNE R1,#0C0H,AHEAD
	MOV PC,#SNDLY2


AHEAD:SJMP $ ;-------ADD DAC------




	



;;-------------ALL CALLS ------------------------;;

WLCMMSG:DB "WELCOME TO MSU BARODA!"
FNLMSG:DB "FINAL YEAR PROJECT!"
SLTSINE:DB "SELECT WAVEFORM YOU WANT TO SEE!"
WV_TYPE:DB "1  SINE WAVE    2  3RD HARMONIC!"
FRQ:DB "1 25Hz  2  50Hz 3 100Hz!"

	;-------KEYBOARD INTERFACING-----

KBD:LCALL KEYBOARD
	MOV A,NEWKEY
	CJNE A,#RSTKY,NXT
	LJMP START
NXT:CJNE A,#OKKEY,NXT1
	;----- SOME LOGIC----ADD HERE
	RET
NXT1:CJNE A,#DOWNKEY,NXT2
	CJNE R1,#0C0H,NX
	MOV A,#80H
	MOV R1,A
	LCALL WRTCMD
	SJMP KBD
NX: MOV A,#0C0H
	MOV R1,A
	LCALL WRTCMD
	SJMP KBD
NXT2:CJNE A,UPKEY,NXT3
	CJNE R1,#80H,NX1
	MOV A,#0C0H
	MOV R1,A
	LCALL WRTCMD
	SJMP KBD
NX1:MOV A,#80H
	MOV R1,A
	LCALL WRTCMD
NXT3:	SJMP KBD

KEYBOARD:MOV P1,#0FH		; MAKING AS READING PORT
WAIT:LCALL KEYSDOWN			; CHECK IF NO KEY IS PRESSED OR NOT
	JZ WAIT
	LCALL CONVERT			;CHECK FOR SINGLE KEY IS PRESSED OR NOT
	JNB VALIDKEY,WAIT
	MOV NEWKEY,A
	MOV R4,#01H			; --??? DECLARING OF NEWKEY && VALIDKEY REMAINING.
	LCALL DELAY1					; --??? DELAY FOR KEYBOARD NOISE IS REMAINIG
	LCALL KEYSDOWN
	JZ WAIT
	LCALL CONVERT
	JNB VALIDKEY,WAIT
	CJNE A,NEWKEY,WAIT
	RET

CONVERT:CLR VALIDKEY
	CLR A
	MOV A,P1
	ORL A, #0F0H
	CJNE A,	#UPKEY,CH1
	SJMP FOUND
CH1:CJNE A, #DOWNKEY,CH2
	SJMP FOUND
CH2:CJNE A, #OKKEY,CH3
	SJMP FOUND
CH3:CJNE A, #RSTKY,CH4
FOUND:SETB VALIDKEY
CH4:RET

KEYSDOWN:MOV A,P1	; LAST 4 PIN OF THE PORT P2 FOR UP,DOWN,OKAY,RESET
	ORL A, #0F0H
	CPL A
	RET

;----delay subroutine---
DELAY:MOV R4,#3		; ADD NUMBER OF SEC 
DELAY1:MOV R5,#10	; FROM HERE ---1 SECOND DELAY
D2:	MOV R6,#200
D1:	MOV R7,#250
HERE:DJNZ R7,HERE
	DJNZ R6,D1
	DJNZ R5,D2
	DJNZ R4,DELAY1
	RET

	;--------DELAY FOR SINE WAVE SMOTHNESS-------------


SNDLY:MOV R3,#55
	DJNZ R3,$
	RET
SNDLY1:MOV R3,#111
	DJNZ R3,$
	RET
SNDLY2:MOV R3,#222
	DJNZ R3,$
	RET

;-----display 16 character in LCD---

DISP_MSG:MOV A,#01H		; CLEAR LCD BEFORE DISPLAYING OTHER MSG
	LCALL WRTCMD
	MOV A,#80H	; FORCE CURSOR POSITION TO FIRST
	LCALL WRTCMD
	MOV B,#16	; FOR 16 CHARACTER  IN THE MSG BODY
L1:	CLR A
	MOVC A, @A+ DPTR
	CJNE A,#21H,CON1	;COMPARING '!' WITH ASCII 21H SO THAT END OF MSG AND EXIT LOOP
	SJMP RETURN
CON1:LCALL WRT_DATA
	INC DPTR
	DJNZ B,L1	; WHEN IT EXIT 1ST LINE WILL DISPLAY 16 CHARACTER
	MOV A,#0C0H	; SENDING CURSOR TO 2ND ROW FIRST POSTION
	LCALL WRTCMD
	MOV B,#16
L2: CLR A
	MOVC A,@A+DPTR
	CJNE A,#21H,CON2	;COMPARING '!' WITH ASCII 21h
	SJMP RETURN
CON2:LCALL WRT_DATA
	INC DPTR
	DJNZ B,L2
RETURN:RET



;------command and write subroutine for LCD---

WRTCMD:LCALL ISREADY	
	MOV p2,A
	CLR p3.7	; RS = 0 FOR COMMAND
	CLR P1.3	; R/W = 0 FOR WRITTING 
	SETB p3.6	; ENABLE SIGNAL
	CLR p3.6
	RET

WRT_DATA:LCALL ISREADY
	MOV p2,A
	SETB p3.7	; RS = 1 FOR DATA
	CLR P1.3	; R/W = 0 FOR WRITTING TO DISPLAY
	SETB p3.6	;ENABLE SIGNAL
	CLR P2.2	 
	RET

;-----check if D7 bit is busy or not---

ISREADY:SETB p2.7	; READING AS INPUT BIT OR PORT
	CLR p3.7	  ; RS = 0 AS COMMAND
	SETB P1.3	; R/W = 1 FOR READING COMMAND
BUSY:CLR p3.6	; ENABLE SIGNAL
	SETB p3.6
	JB p2.7,BUSY
	CLR p3.6
	RET

	END
